# Generated by Django 3.1.7 on 2021-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_list', '0003_auto_20210227_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='add_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
